apiVersion: v1 
kind: ConfigMap 
metadata:
  name: pod-config-details

data:
  course: "devops"
  trainer: "siva"
  duration: "100hrs"  
  pod: "ising nginx containers"


#ANSIBLE environment: VARIABLES

#ENV course="devops"
 #   trainer="siva"
 #   duration="100hrs"  

